name: ika_smansara
description: IKA SMANSARA
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  chopper: ^7.0.1
  crypto: ^3.0.3
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.1.5+1
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_dynamic_links: ^5.3.4
  firebase_in_app_messaging: ^0.7.3+4
  firebase_messaging: ^14.6.5
  firebase_performance: ^0.9.2+4
  firebase_remote_config: ^4.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.0.4
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.1
  logging: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
  webview_flutter_platform_interface: ^2.4.0
  webview_flutter_web: ^0.2.2+1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  chopper_generator: ^7.0.1
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true

