name: ika_smansara
description: IKA SMANSARA
version: 1.0.4+5
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  appwrite: ^11.0.1
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  currency_formatter: ^2.1.0
  dio: ^5.4.0
  expandable_text: ^2.3.0
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.2.1+4
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_dynamic_links: ^5.3.4
  firebase_in_app_messaging: ^0.7.3+4
  firebase_messaging: ^14.6.5
  firebase_performance: ^0.9.2+4
  firebase_remote_config: ^4.2.4
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.0.4
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^16.1.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.2.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  group_button: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.6
  json_annotation: ^4.8.1
  logger: ^2.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod_annotation: ^2.3.3
  url_launcher: ^6.1.12

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo_icon_ika.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
