name: ika_smansara
description: IKA SMANSARA
version: 1.0.4+5
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_responsive_util:
    git:
      url: https://github.com/MashudiSudonym/adaptive_responsive_util.git
      ref: master
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  chopper: ^7.0.9
  crypto: ^3.0.3
  currency_formatter: ^2.1.0
  dartz: ^0.10.1
  expandable_text: ^2.3.0
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.2.1+4
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_dynamic_links: ^5.3.4
  firebase_in_app_messaging: ^0.7.3+4
  firebase_messaging: ^14.6.5
  firebase_performance: ^0.9.2+4
  firebase_remote_config: ^4.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.0.4
  flutter_form_bloc: ^0.31.0
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.5.0
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  group_button: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  logger: ^2.0.1
  logging: ^1.2.0
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.0.15
  url_launcher: ^6.1.12

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  chopper_generator: ^7.0.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo_icon_ika.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - lib/common/utils/

flutter_gen:
  integrations:
    flutter_svg: true

