name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]
    paths:
      - '_config.yml'
      - '_layouts/**'
      - '_includes/**'
      - 'assets/**'
      - 'index.md'
      - '_pages/**'
      - 'docs/**'
      - '.github/workflows/jekyll.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '_config.yml'
      - '_layouts/**'
      - '_includes/**'
      - 'assets/**'
      - 'index.md'
      - '_pages/**'
      - 'docs/**'
      - '.github/workflows/jekyll.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Build with Jekyll
      run: |
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        cname: ika-smansara-app.github.io